### PR TITLE
switch to "delegate_to: localhost" for purge playbook

### LINKED ISSUE #170: Purge behavior when calling `cephadm-purge-cluster.yml` with `--limit`
The `cephadm-purge-cluster.yml` pre-purge checks fail in a not-so-good way when one calls the playbook with a `--limit` to a subset of the hosts in the inventory (e.g., those hosts that are in the cluster).

As an alternative, the plays could have `hosts: all` set and the following added to each task to achieve the same behavior in a compatible way:

```
      delegate_to: localhost
      run_once: true
```

Otherwise, once sees `skipping: no hosts matched` on the applicable plays. The "confirm whether user really wants to purge the cluster" play even prompts the user to see if they want to purge the cluster, but continues to purge the cluster no matter what they type.

If this sounds like an acceptable solution I can make a PR.

### PR DESCRIPTION
**Pull request by tobiasmcnulty**
This PR fixes #170.

I noticed a few other references to `hosts: localhost` in other playbooks I haven't used; should I update these the same way?

```
$ grep -rn 'hosts: localhost' .
./validate/preflight.yml:9:- hosts: localhost
./validate/insecure-registries.yml:6:- hosts: localhost
./rocksdb-resharding.yml:25:- hosts: localhost
./cephadm-clients.yml:29:  hosts: localhost
```

# Q/A
With the fix in place, passing `-l` to the playbook allows it to abort after the prompt:
```
$ ansible-playbook -i inventory -l ceph cephadm-ansible/cephadm-purge-cluster.yml -e fsid=bcf88dfa-3cf0-11ed-b5a4-b19cff2a0492

PLAY [check local prerequisites are in place] ************************************************************************************************************

TASK [fail if fsid was not provided] *********************************************************************************************************************
skipping: [loyal_mouse]

TASK [fail if admin group doesn't exist or is empty] *****************************************************************************************************
skipping: [loyal_mouse]

PLAY [check keyring is present on the admin host] ********************************************************************************************************

TASK [check /etc/ceph/ceph.admin.client.keyring] *********************************************************************************************************
ok: [loyal_mouse]

TASK [fail if /etc/ceph/admin.client.keyring is not present] *********************************************************************************************
skipping: [loyal_mouse]

PLAY [check cluster hosts have cephadm and the required fsid bcf88dfa-3cf0-11ed-b5a4-b19cff2a0492] *******************************************************

TASK [check cephadm binary is available] *****************************************************************************************************************
ok: [loyal_mouse]
ok: [tidy_piglet]
ok: [tender_poodle]

TASK [fail if cephadm is not available] ******************************************************************************************************************
skipping: [loyal_mouse]
skipping: [tender_poodle]
skipping: [tidy_piglet]

TASK [check fsid directory given is valid across the cluster] ********************************************************************************************
ok: [tender_poodle]
ok: [tidy_piglet]
ok: [loyal_mouse]

TASK [fail if the fsid directory is missing] *************************************************************************************************************
skipping: [loyal_mouse]
skipping: [tender_poodle]
skipping: [tidy_piglet]

Are you sure you want to purge the cluster with fsid=bcf88dfa-3cf0-11ed-b5a4-b19cff2a0492 ?
 [no]: no

PLAY [confirm whether user really wants to purge the cluster] ********************************************************************************************

TASK [exit playbook, if user did not mean to purge cluster] **********************************************************************************************
fatal: [loyal_mouse -> localhost]: FAILED! => {"changed": false, "msg": "Exiting cephadm-purge-cluster playbook, cluster was NOT purged.\nTo purge the cluster, either say 'yes' at the prompt or use `-e ireallymeanit=yes`\non the command line when invoking the playbook\n"}

NO MORE HOSTS LEFT ***************************************************************************************************************************************

PLAY RECAP ***********************************************************************************************************************************************
loyal_mouse                : ok=3    changed=0    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0   
tender_poodle              : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
tidy_piglet                : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0  
```

### CODE REVIEW

**Comment by guits** [comment]
@tobiasmcnulty yes, i think it makes sense to change it everywere 🙁

**Comment by guits** [comment]
@tobiasmcnulty ? 🙂

**Comment by tobiasmcnulty** [comment]
@guits Thanks for the ping! I've been distracted with other things but I hope to get back to this very soon.

**Comment by guits** [comment]
@tobiasmcnulty do you want someone to take over this PR ?

**Pull request closed without merging**
