### PR TITLE
tests: use cephadm defaults image

### PR DESCRIPTION
**Pull request by guits**
So we don't have to maintain this in the tox.ini file.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Review by asm0deuz — APPROVED** [review]

**Comment by ronen-fr** [comment]
@guits : "shaman" now fails (for non-Pacific versions) with "Error: Failed to download metadata for repo 'powertools': Cannot prepare internal mirrorlist: No URLs in mirrorlist"

**Comment by guits** [comment]
@ronen-fr could you elaborate a bit more? what are you trying to achieve exactly? which OS are you running on?

**Comment by ronen-fr** [comment]
@guits: not me personally... see https://shaman.ceph.com/builds/ceph/
Most builds now fail. See for example:
https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/60223//consoleFull

**Comment by guits** [comment]
@ronen-fr  i'm unsure to understand what is the relation with this PR.
shaman is facing the same issue I got in this project, it has to move to CentOS stream 8 since CentOS 8 is no longer supported.

**Comment by ronen-fr** [comment]
> @ronen-fr i'm unsure to understand what is the relation with this PR.

It was suggested as the cause, as the timing of the Shaman problem coincides with the PR, and the subject matter is similar.
Anyway - I'll leave it to Shaman's maintainers.

**Pull request merged**
