### PR TITLE
tests: use ceph/ceph:v16 on pacific branch

### PR DESCRIPTION
**Pull request by guits**
Test with `latest-pacific` tag.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
Why aren't we using the ceph/ceph:v16.2 image instead of the daemon-base one ?

**Comment by guits** [comment]
> Why aren't we using the ceph/ceph:v16.2 image instead of the daemon-base one ?

from the discussion we just got, I think we can :slightly_smiling_face:

**Review by sebastian-philipp — APPROVED** [review]

**Comment by dsavineau** [comment]
jenkins test cephadm-ansible-prs-all_daemons

**Comment by dsavineau** [comment]
jenkins test cephadm-ansible-prs-all_daemons

**Comment by dsavineau** [comment]
jenkins test all_daemons

**Comment by dsavineau** [comment]
jenkins test all_daemons

**Pull request merged**
