### PR TITLE
Add rocksdb resharding playbook

### PR DESCRIPTION
**Pull request by guits**
This adds a new playbook "rocksdb-resharding"

### CODE REVIEW

**Comment by guits** [comment]
@neha-ojha @vumrao

**Comment by vumrao** [comment]
@aclamk

**Comment by vumrao** [comment]
LGTM!

**Review by vumrao — APPROVED** [review]

**Comment by neha-ojha** [comment]
> @neha-ojha @vumrao

Thanks @guits!

**Pull request merged**
